# Generated by Django 4.2 on 2026-01-13 13:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fonte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('url_base', models.URLField(max_length=500, unique=True)),
                ('tipo_coleta', models.CharField(choices=[('RSS', 'RSS'), ('API', 'API'), ('SCRAPING', 'Scraping')], max_length=20)),
                ('url_rss_api', models.URLField(blank=True, max_length=500, null=True)),
                ('data_cadastro', models.DateTimeField(auto_now_add=True)),
                ('ativo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Municipio',
            fields=[
                ('id_municipio', models.IntegerField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('regiao', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Pauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Noticia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=500)),
                ('url', models.URLField(max_length=1000, unique=True)),
                ('data_publicacao', models.DateTimeField()),
                ('conteudo', models.TextField()),
                ('texto_resumo', models.TextField()),
                ('coletado_em', models.DateTimeField(auto_now_add=True)),
                ('deduplicado', models.BooleanField(default=False)),
                ('acessos', models.IntegerField(default=0)),
                ('fonte', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.fonte')),
            ],
        ),
        migrations.CreateModel(
            name='ClassificacaoPauta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_classificacao', models.CharField(choices=[('AUTOMATICO', 'Automático'), ('MANUAL', 'Manual')], max_length=20)),
                ('data_classificacao', models.DateTimeField(auto_now_add=True)),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.noticia')),
                ('pauta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pauta')),
            ],
            options={
                'unique_together': {('noticia', 'pauta')},
            },
        ),
        migrations.CreateModel(
            name='ClassificacaoMunicipio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('metodo_classificacao', models.CharField(choices=[('AUTOMATICO', 'Automático'), ('MANUAL', 'Manual')], max_length=20)),
                ('data_classificacao', models.DateTimeField(auto_now_add=True)),
                ('municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.municipio')),
                ('noticia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.noticia')),
            ],
            options={
                'unique_together': {('noticia', 'municipio')},
            },
        ),
    ]
